DS-3755 Update to ruby 3.2.*
LoyaltyNZ/CASino pull request #23
Opened 2023-10-16 03:17 UTC by ildomar-grings

## Overview

[DS-3755](https://loyaltynz.atlassian.net/browse/DS-3755)

## What is the change?

## How was this change made?

## How do I use/reproduce this change?

## Notes

2023-10-16 04:10 UTC, loyaltynz-svc-cicd commented
There were errors. https://jenkins.loyaltydevops.co.nz/job/SharedTools/job/casino/job/PRCheck/24/

2023-10-16 22:23 UTC, davidoram reviewed
One change around files included in the gem

2023-10-16 22:23 UTC, davidoram commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
@ildomar-grings I think this needs to be changed to something like [this](https://github.com/LoyaltyNZ/loyalty_platform_authentication/blob/master/loyalty_platform_authentication.gemspec#L12-L13).  Otherwise it might create an empty gem, devoid of any files

2023-10-16 22:28 UTC, ildomar-grings commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
I had this fear, so I tested it locally, seems to work just fine:
![image](https://github.com/LoyaltyNZ/CASino/assets/98503264/5058ba8f-7458-4209-9ee2-8603df5f6e6b)

2023-10-16 22:31 UTC, ildomar-grings commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
![image](https://github.com/LoyaltyNZ/CASino/assets/98503264/f51d9c34-5cbc-4ca9-9777-06ee54c93446)

2023-10-16 22:35 UTC, ildomar-grings commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/casino-5.2.14/lib/casino

2023-10-16 22:36 UTC, korolkovas approved these changes
cicd 👍

2023-10-16 22:38 UTC, nickpiercy95 commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
My understanding, limited as it is, is that `ls-files` shows _git-specific_ information related to the combination of the files in the remote repository, local repository, and any changes (staged or otherwise) in the local filesystem. I imagine it probably works as-is, but I agree with Dave that a regular shell glob is probably better given we know exactly what it's doing.

2023-10-16 22:43 UTC, ildomar-grings commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
Ok, Lemme try

2023-10-16 22:55 UTC, ildomar-grings commented on casino.gemspec
>    s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
![path](https://github.com/LoyaltyNZ/CASino/assets/98503264/703e69d4-f3f9-4c1b-9cf7-4a7bd27df875)

2023-10-16 22:59 UTC, nickpiercy95 requested changes

2023-10-16 22:59 UTC, nickpiercy95 commented on casino.gemspec
> +  s.files         = Dir.glob( 'lib/**/*.rb' ) + Dir.glob( 'db/**/*.rb' )
Do you need `app` as well? I think since the original was `git ls-files` (ie. _everything_) maybe this would give the result we want:
```suggestion
  s.files         = Dir.glob( '**/*' )
```

2023-10-16 23:04 UTC, ildomar-grings commented on casino.gemspec
> +  s.files         = Dir.glob( 'lib/**/*.rb' ) + Dir.glob( 'db/**/*.rb' )
Unsure. Checking

2023-10-16 23:13 UTC, ildomar-grings commented on casino.gemspec
> +  s.files         = Dir.glob( 'lib/**/*.rb' ) + Dir.glob( 'db/**/*.rb' )
Made some changes.
I'm not a fan of loading everything in the package. Because this definition of files-list exists for a reason, right?

2023-10-17 00:10 UTC, nickpiercy95 commented on casino.gemspec
> +  s.files         = Dir.glob( 'lib/**/*.rb' ) + Dir.glob( 'db/**/*.rb' )
Good point, approved 👍 

Btw you can save time by doing this instead :)

```ruby
Dir.glob( '{app,config,db,lib,public}/**/*.rb' )
```

2023-10-17 00:11 UTC, nickpiercy95 approved these changes

2023-10-17 00:24 UTC, ildomar-grings commented on casino.gemspec
> +  s.files         = Dir.glob( 'lib/**/*.rb' ) + Dir.glob( 'db/**/*.rb' )
That is a good one. 
Tested locally, it created the package well. 
Code updated.

2023-10-17 00:27 UTC, merged